/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#000000",
        "on-background": "#e2e2e2",
        "secondary-container": "#3f4944",
        "on-surface-variant": "#bccac0",
        "on-tertiary-fixed": "#0f1f18",
        "primary-fixed-dim": "#59dda9",
        "primary": "#59dda9",
        "primary-fixed": "#78fac3",
        "on-primary-fixed-variant": "#005138",
        "secondary": "#bfc9c2",
        "surface-container-highest": "#353535",
        "on-error": "#690005",
        "on-surface": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "secondary-fixed-dim": "#bfc9c2",
        "outline-variant": "#3d4a42",
        "on-primary-container": "#003422",
        "tertiary-fixed-dim": "#b8cbc0",
        "on-tertiary": "#24342d",
        "tertiary-container": "#86988e",
        "on-error-container": "#ffdad6",
        "tertiary": "#b8cbc0",
        "surface-dim": "#131313",
        "primary-container": "#00a878",
        "tertiary-fixed": "#d4e7dc",
        "error-container": "#93000a",
        "on-primary-fixed": "#002114",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed": "#141d19",
        "on-secondary": "#29322e",
        "on-secondary-container": "#adb8b1",
        "on-tertiary-fixed-variant": "#3a4a43",
        "outline": "#86948b",
        "inverse-on-surface": "#303030",
        "surface-variant": "#353535",
        "surface-container": "#1f1f1f",
        "surface": "#131313",
        "surface-container-low": "#1b1b1b",
        "on-primary": "#003826",
        "surface-container-high": "#2a2a2a",
        "surface-bright": "#393939",
        "on-secondary-fixed-variant": "#3f4944",
        "surface-tint": "#59dda9",
        "on-tertiary-container": "#203029",
        "error": "#ffb4ab",
        "secondary-fixed": "#dbe5de",
        "inverse-primary": "#006c4c"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
